package com.its.easyjavadropbox.api.interfaces;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.List;

import com.dropbox.core.DbxClient;
import com.dropbox.core.DbxEntry;
import com.dropbox.core.DbxEntry.WithChildren;
import com.dropbox.core.DbxException;

public interface EasyJavaDropBoxService {
	/**
	 * 
	 * @return all files for dropboxPath
	 * @throws DbxException
	 */
	List<DbxEntry> listFiles() throws DbxException;


	/**
	 * 
	 * @param token generated by dropbox api
	 * @return  files/folders for dropboxpath specified
	 * @throws DbxException 
	 */
	WithChildren getListing() throws DbxException;

	/**
	 * 
	 * @param basePath inform the path of the file 
	 * @param query  what you wish search 
	 * @return 
	 * @throws DbxException 
	 */
	List<DbxEntry> searchFile(String basePath, String query) throws DbxException;

	DbxClient getClient();
	
	/**
	 * 
	 * @param newpath must be absolute path 
	 * e.g: /nameOfFolder
	 */
	void changeDropboxPath(String newpath);
	/**
	 * 
	 * @param ident inform xs, s, m ,l , xl
	 * @param fileName 
	 * @param width
	 * @param height
	 * @param outputStream
	 * @throws IOException 
	 * @throws DbxException 
	 */
	public void writeThumbnail(String ident, int width, int height,String fileName, OutputStream outputStream) throws DbxException, IOException;
	
	
	/**
	 * 
	 * @param finalName inform finalName of the file e.g: myphoto.png
	 * @param inputStreamContent  content Stream of file 
	 * @throws DbxException
	 * @throws IOException
	 */
	public void saveToDropbox(String finalName,InputStream inputStreamContent) throws DbxException,IOException;

}
